name: Get Transactions from NetFile API and store in GitHub
on:
#   schedule:
#     # run at 4am PT / 11am UTC every day of the week
#     - cron:  '0 11 * * */1'
  workflow_dispatch:

jobs:
  run_download:
    strategy:
      matrix: 
        year: [ 2020, 2019, 2018 ] # used to indicate which years to get transactions for
    name: Retrieving ${{ matrix.year }} transactions
    if: github.repository == 'opensandiego/sdvv-frontend'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - name: Downloading from NetFile API
        run: "node ./src/scripts/download_transactions_to_csv.js --aid=32 --year=${{ matrix.year }}"
      - name: Uploading to GitHub Artifact
        uses: actions/upload-artifact@v2
        with:
          name: netfile-csv-transactions-data-${{ matrix.year }}
          path: src/assets/data/netfile_api_${{ matrix.year }}.csv
